// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://t.me/GusGus153",
        "contact": {
            "name": "Goose",
            "url": "https://t.me/GusGus153"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "post": {
                "description": "Add one task",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "AddTask",
                "parameters": [
                    {
                        "description": "Request body in JSON format",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.TaskType"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/server/add/{id}/{add}": {
            "post": {
                "description": "Add some worker",
                "tags": [
                    "Server"
                ],
                "summary": "AddWorker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "workers",
                        "name": "add",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/server/all": {
            "get": {
                "description": "Get all server",
                "tags": [
                    "Server"
                ],
                "summary": "AllServer",
                "responses": {}
            }
        },
        "/server/del/{id}": {
            "delete": {
                "description": "Delete one server",
                "tags": [
                    "Server"
                ],
                "summary": "DeleteServer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/task/{id}": {
            "get": {
                "description": "Get one task",
                "tags": [
                    "Task"
                ],
                "summary": "GetTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/user/{id}": {
            "get": {
                "description": "Get info about user",
                "tags": [
                    "User"
                ],
                "summary": "GetUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "docs.TaskType": {
            "type": "object",
            "properties": {
                "add_time": {
                    "type": "string"
                },
                "dev_time": {
                    "type": "string"
                },
                "mult_time": {
                    "type": "string"
                },
                "sub_time": {
                    "type": "string"
                },
                "task": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Вычислитель арифметических выражений(AEC)",
	Description:      "Сервис для параллельного вычисления арифметических выражений",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
